import { css } from '../../../styled-system/css';

export const tableStyles = {
    section: css({
        display: 'flex',
        flexDirection: 'column',
        gap: '4',
        borderRadius: 'md',
        bg: 'white',
        p: { base: '3', md: '4' },
        boxShadow: 'sm',
    }),
    sectionHeader: css({
        display: 'flex',
        flexDirection: { base: 'column', md: 'row' },
        justifyContent: { base: 'flex-start', md: 'space-between' },
        alignItems: { base: 'flex-start', md: 'center' },
        pb: '2',
        borderBottom: '1px solid',
        borderColor: 'gray.200',
    }),
    sectionTitle: css({
        fontSize: { base: 'lg', md: '2xl' },
        fontWeight: 'bold',
        color: 'gray.900',
    }),
    stats: css({
        width: '100%',
        display: 'flex',
        gap: { base: '2', md: '4' },
        fontSize: 'sm',
        color: 'gray.700',
        justifyContent: 'space-around',
    }),
    statsItem: css({
        display: 'flex',
        flexDirection: 'column',
        gap: '1',
        flex: 1,
        textAlign: 'center',
    }),
    statsLabel: css({
        fontSize: 'xs',
        color: 'gray.500',
        fontWeight: '500',
        textTransform: 'uppercase',
    }),
    statsValue: css({
        fontSize: { base: 'lg', md: 'xl' },
        fontWeight: 'bold',
        color: 'gray.900',
    }),
    tableWrapper: css({
        overflowX: 'auto',
        borderRadius: 'md',
        border: '1px solid',
        borderColor: 'gray.200',
    }),
    table: css({
        width: '100%',
        borderCollapse: 'collapse',
        fontSize: { base: 'xs', md: 'sm' },
    }),
    thead: css({
        bg: 'gray.50',
        fontWeight: '600',
        color: 'gray.700',
        textAlign: 'left',
        fontSize: 'xs',
        textTransform: 'uppercase',
    }),
    th: css({
        px: { base: '2', md: '3' },
        py: '2',
        borderBottom: '1px solid',
        borderColor: 'gray.200',
        fontSize: { base: '0.65rem', md: 'xs' },
    }),
    tbody: css({
        bg: 'white',
    }),
    tr: css({
        borderBottom: '1px solid',
        borderColor: 'gray.100',
        _hover: {
            bg: 'gray.50',
        },
    }),
    td: css({
        px: { base: '2', md: '3' },
        py: '2',
        color: 'gray.700',
        fontSize: { base: '0.75rem', md: 'sm' },
    }),
    categoryCell: css({
        display: 'flex',
        alignItems: 'center',
        gap: '2',
    }),
    categoryBadge: css({
        display: 'inline-flex',
        alignItems: 'center',
        justifyContent: 'center',
        px: '2',
        py: '1',
        borderRadius: 'sm',
        fontSize: 'xs',
        fontWeight: '500',
        border: '1px solid',
        whiteSpace: 'nowrap',
    }),
    price: css({
        textAlign: 'right',
        fontVariantNumeric: 'tabular-nums',
    }),
    deleteButton: css({
        px: '2',
        py: '1',
        bg: 'red.500',
        color: 'white',
        border: 'none',
        borderRadius: 'sm',
        cursor: 'pointer',
        fontSize: { base: '0.65rem', md: 'xs' },
        fontWeight: '500',
        _hover: {
            bg: 'red.600',
        },
    }),
    moveButton: css({
        px: '2',
        py: '1',
        bg: 'blue.500',
        color: 'white',
        border: 'none',
        borderRadius: 'sm',
        cursor: 'pointer',
        fontSize: { base: '0.65rem', md: 'xs' },
        fontWeight: '500',
        _hover: {
            bg: 'blue.600',
        },
    }),
    addForm: css({
        display: 'flex',
        flexDirection: 'column',
        gap: '3',
        p: { base: '3', md: '4' },
        bg: 'gray.50',
        borderRadius: 'md',
        border: '1px solid',
        borderColor: 'gray.200',
    }),
    formRow: css({
        display: 'grid',
        gridTemplateColumns: {
            base: '1fr',
            sm: 'repeat(2, 1fr)',
            lg: 'repeat(auto-fit, minmax(150px, 1fr))',
        },
        gap: '3',
    }),
    formGroup: css({
        display: 'flex',
        flexDirection: 'column',
        gap: '1',
    }),
    label: css({
        fontSize: 'sm',
        fontWeight: '500',
        color: 'gray.700',
    }),
    input: css({
        px: '2',
        py: '1',
        border: '1px solid',
        borderColor: 'gray.300',
        borderRadius: 'sm',
        fontSize: 'sm',
        _focus: {
            outline: 'none',
            borderColor: 'blue.500',
            boxShadow: '0 0 0 2px rgba(59, 130, 246, 0.1)',
        },
    }),
    select: css({
        px: '2',
        py: '1',
        border: '1px solid',
        borderColor: 'gray.300',
        borderRadius: 'sm',
        fontSize: 'sm',
        bg: 'white',
        cursor: 'pointer',
        _focus: {
            outline: 'none',
            borderColor: 'blue.500',
            boxShadow: '0 0 0 2px rgba(59, 130, 246, 0.1)',
        },
    }),
    button: css({
        px: { base: '3', md: '4' },
        py: { base: '2', md: '2' },
        bg: 'blue.500',
        color: 'white',
        border: 'none',
        borderRadius: 'sm',
        fontWeight: '500',
        cursor: 'pointer',
        fontSize: { base: 'sm', md: 'base' },
        _hover: {
            bg: 'blue.600',
        },
    }),
    emptyState: css({
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        py: { base: '6', md: '8' },
        px: { base: '3', md: '4' },
        color: 'gray.500',
        textAlign: 'center',
    }),
    emptyStateIcon: css({
        fontSize: '3xl',
        mb: '2',
    }),
    emptyStateText: css({
        fontSize: 'sm',
        color: 'gray.500',
    }),
    mobileCardList: css({
        display: { base: 'flex', md: 'none' },
        flexDirection: 'column',
        gap: '1',
    }),
    mobileCard: css({
        display: 'flex',
        flexDirection: 'column',
        gap: '2',
        px: '3',
        py: '2',
        width: '100%',
        bg: 'white',
        borderRadius: 'md',
        border: '1px solid',
        borderColor: 'gray.200',
        cursor: 'move',
        _hover: {
            borderColor: 'blue.300',
            boxShadow: '0 2px 8px rgba(0, 0, 0, 0.1)',
        },
    }),
    dragging: css({
        opacity: '0.5',
        borderColor: 'blue.500',
        boxShadow: '0 4px 12px rgba(59, 130, 246, 0.3)',
    }),
    swiped: css({
        borderColor: 'red.500 !important',
        borderWidth: '2px !important',
        bg: 'red.100 !important',
        boxShadow: '0 4px 12px rgba(239, 68, 68, 0.5) !important',
    }),
    swipeContainer: css({
        position: 'relative',
        display: 'block',
        width: '100%',
        overflow: 'hidden',
        borderRadius: 'md',
    }),
    swipeBackground: css({
        position: 'absolute',
        inset: '0',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'flex-end',
        paddingRight: '4',
        fontSize: '3xl',
        fontWeight: 'bold',
        zIndex: '0',
        borderRadius: 'md',
    }),
    swipeBackgroundDelete: css({
        bg: 'red.500',
        color: 'white',
    }),
    swipeBackgroundMove: css({
        bg: 'blue.500',
        color: 'white',
    }),
    swipeCardWrapper: css({
        position: 'relative',
        zIndex: '1',
    }),
    cardButton: css({
        background: 'none',
        border: 'none',
        padding: '0',
        cursor: 'pointer',
        display: 'flex',
        flexDirection: 'column',
        gap: '2',
        textAlign: 'left',
        _focus: {
            outline: 'none',
        },
    }),
    cardRow: css({
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        gap: '2',
        flexWrap: 'wrap',
    }),
    cardLabel: css({
        fontSize: 'xs',
        color: 'gray.500',
        fontWeight: '500',
    }),
    cardValue: css({
        fontSize: 'sm',
        fontWeight: 'bold',
        color: 'gray.900',
    }),
    modalOverlay: css({
        position: 'fixed',
        inset: '0',
        bg: 'rgba(0, 0, 0, 0.5)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: '50',
        p: '4',
    }),
    modalContent: css({
        bg: 'white',
        borderRadius: 'lg',
        p: '6',
        maxWidth: '500px',
        width: '100%',
        maxHeight: '90vh',
        overflowY: 'auto',
        boxShadow: '0 10px 40px rgba(0, 0, 0, 0.2)',
    }),
    modalHeader: css({
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        mb: '4',
        pb: '4',
        borderBottom: '1px solid',
        borderColor: 'gray.200',
    }),
    modalTitle: css({
        fontSize: 'xl',
        fontWeight: 'bold',
        color: 'gray.900',
    }),
    closeButton: css({
        bg: 'transparent',
        border: 'none',
        fontSize: 'lg',
        color: 'gray.500',
        cursor: 'pointer',
        _hover: {
            color: 'gray.900',
        },
    }),
    modalBody: css({
        display: 'flex',
        flexDirection: 'column',
        gap: '4',
        mb: '4',
    }),
    modalField: css({
        display: 'flex',
        flexDirection: 'column',
        gap: '1',
    }),
    modalFieldLabel: css({
        fontSize: 'sm',
        fontWeight: '600',
        color: 'gray.700',
    }),
    modalFieldValue: css({
        fontSize: 'base',
        color: 'gray.900',
    }),
    modalActions: css({
        display: 'flex',
        gap: '2',
        pt: '4',
        borderTop: '1px solid',
        borderColor: 'gray.200',
    }),
    modalDeleteButton: css({
        flex: '1',
        px: '4',
        py: '2',
        bg: 'red.500',
        color: 'white',
        border: 'none',
        borderRadius: 'sm',
        fontWeight: '500',
        cursor: 'pointer',
        fontSize: 'sm',
        _hover: {
            bg: 'red.600',
        },
    }),
    modalMoveButton: css({
        flex: '1',
        px: '4',
        py: '2',
        bg: 'blue.500',
        color: 'white',
        border: 'none',
        borderRadius: 'sm',
        fontWeight: '500',
        cursor: 'pointer',
        fontSize: 'sm',
        _hover: {
            bg: 'blue.600',
        },
    }),
    desktopTable: css({
        display: { base: 'none', md: 'block' },
    }),
    titleRow: css({
        width: '100%',
        display: 'flex',
        justifyContent: 'flex-end',
        alignItems: 'center',
        gap: '1rem',
        mb: '2',
    }),
    addButton: css({
        p: '0.25rem 0.5rem',
        bg: 'blue.500',
        color: 'white',
        borderRadius: 'md',
        border: 'none',
        fontWeight: 'bold',
        cursor: 'pointer',
        fontSize: 'lg',
        lineHeight: '1',
        minWidth: '2rem',
        minHeight: '2rem',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        flexShrink: 0,
        _hover: {
            bg: 'blue.600',
        },
    }),
} as const;
