import { css } from '../../../styled-system/css';

export const tableStyles = {
    section: css({
        display: 'flex',
        flexDirection: 'column',
        gap: '4',
        mb: '6',
        borderRadius: 'md',
        bg: 'white',
        p: '4',
        boxShadow: 'sm',
    }),
    sectionHeader: css({
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        mb: '4',
        pb: '2',
        borderBottom: '1px solid',
        borderColor: 'gray.200',
    }),
    sectionTitle: css({
        fontSize: '2xl',
        fontWeight: 'bold',
        color: 'gray.900',
    }),
    stats: css({
        display: 'flex',
        gap: '4',
        fontSize: 'sm',
        color: 'gray.700',
    }),
    statsItem: css({
        display: 'flex',
        flexDirection: 'column',
        gap: '1',
    }),
    statsLabel: css({
        fontSize: 'xs',
        color: 'gray.500',
        fontWeight: '500',
        textTransform: 'uppercase',
    }),
    statsValue: css({
        fontSize: 'lg',
        fontWeight: 'bold',
        color: 'gray.900',
    }),
    tableWrapper: css({
        overflowX: 'auto',
        borderRadius: 'md',
        border: '1px solid',
        borderColor: 'gray.200',
    }),
    table: css({
        width: '100%',
        borderCollapse: 'collapse',
        fontSize: 'sm',
    }),
    thead: css({
        bg: 'gray.50',
        fontWeight: '600',
        color: 'gray.700',
        textAlign: 'left',
        fontSize: 'xs',
        textTransform: 'uppercase',
    }),
    th: css({
        px: '3',
        py: '2',
        borderBottom: '1px solid',
        borderColor: 'gray.200',
    }),
    tbody: css({
        bg: 'white',
    }),
    tr: css({
        borderBottom: '1px solid',
        borderColor: 'gray.100',
        _hover: {
            bg: 'gray.50',
        },
    }),
    td: css({
        px: '3',
        py: '2',
        color: 'gray.700',
    }),
    categoryCell: css({
        display: 'flex',
        alignItems: 'center',
        gap: '2',
    }),
    categoryBadge: css({
        display: 'inline-flex',
        alignItems: 'center',
        justifyContent: 'center',
        px: '2',
        py: '1',
        borderRadius: 'sm',
        fontSize: 'xs',
        fontWeight: '500',
        border: '1px solid',
        whiteSpace: 'nowrap',
    }),
    price: css({
        textAlign: 'right',
        fontVariantNumeric: 'tabular-nums',
    }),
    deleteButton: css({
        px: '2',
        py: '1',
        bg: 'red.500',
        color: 'white',
        border: 'none',
        borderRadius: 'sm',
        cursor: 'pointer',
        fontSize: 'xs',
        fontWeight: '500',
        _hover: {
            bg: 'red.600',
        },
    }),
    moveButton: css({
        px: '2',
        py: '1',
        bg: 'blue.500',
        color: 'white',
        border: 'none',
        borderRadius: 'sm',
        cursor: 'pointer',
        fontSize: 'xs',
        fontWeight: '500',
        _hover: {
            bg: 'blue.600',
        },
    }),
    addForm: css({
        display: 'flex',
        flexDirection: 'column',
        gap: '3',
        p: '4',
        bg: 'gray.50',
        borderRadius: 'md',
        border: '1px solid',
        borderColor: 'gray.200',
    }),
    formRow: css({
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(150px, 1fr))',
        gap: '3',
    }),
    formGroup: css({
        display: 'flex',
        flexDirection: 'column',
        gap: '1',
    }),
    label: css({
        fontSize: 'sm',
        fontWeight: '500',
        color: 'gray.700',
    }),
    input: css({
        px: '2',
        py: '1',
        border: '1px solid',
        borderColor: 'gray.300',
        borderRadius: 'sm',
        fontSize: 'sm',
        _focus: {
            outline: 'none',
            borderColor: 'blue.500',
            boxShadow: '0 0 0 2px rgba(59, 130, 246, 0.1)',
        },
    }),
    select: css({
        px: '2',
        py: '1',
        border: '1px solid',
        borderColor: 'gray.300',
        borderRadius: 'sm',
        fontSize: 'sm',
        bg: 'white',
        cursor: 'pointer',
        _focus: {
            outline: 'none',
            borderColor: 'blue.500',
            boxShadow: '0 0 0 2px rgba(59, 130, 246, 0.1)',
        },
    }),
    button: css({
        px: '4',
        py: '2',
        bg: 'blue.500',
        color: 'white',
        border: 'none',
        borderRadius: 'sm',
        fontWeight: '500',
        cursor: 'pointer',
        _hover: {
            bg: 'blue.600',
        },
    }),
    emptyState: css({
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        py: '8',
        px: '4',
        color: 'gray.500',
        textAlign: 'center',
    }),
    emptyStateIcon: css({
        fontSize: '3xl',
        mb: '2',
    }),
    emptyStateText: css({
        fontSize: 'sm',
        color: 'gray.500',
    }),
} as const;
