/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SummaryRouteImport } from './routes/summary'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StocksNewRouteImport } from './routes/stocks/new'
import { Route as StocksIdEditRouteImport } from './routes/stocks/$id/edit'

const SummaryRoute = SummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StocksNewRoute = StocksNewRouteImport.update({
  id: '/stocks/new',
  path: '/stocks/new',
  getParentRoute: () => rootRouteImport,
} as any)
const StocksIdEditRoute = StocksIdEditRouteImport.update({
  id: '/stocks/$id/edit',
  path: '/stocks/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/summary': typeof SummaryRoute
  '/stocks/new': typeof StocksNewRoute
  '/stocks/$id/edit': typeof StocksIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/summary': typeof SummaryRoute
  '/stocks/new': typeof StocksNewRoute
  '/stocks/$id/edit': typeof StocksIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/summary': typeof SummaryRoute
  '/stocks/new': typeof StocksNewRoute
  '/stocks/$id/edit': typeof StocksIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/settings' | '/summary' | '/stocks/new' | '/stocks/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/settings' | '/summary' | '/stocks/new' | '/stocks/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/summary'
    | '/stocks/new'
    | '/stocks/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  SummaryRoute: typeof SummaryRoute
  StocksNewRoute: typeof StocksNewRoute
  StocksIdEditRoute: typeof StocksIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/summary': {
      id: '/summary'
      path: '/summary'
      fullPath: '/summary'
      preLoaderRoute: typeof SummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stocks/new': {
      id: '/stocks/new'
      path: '/stocks/new'
      fullPath: '/stocks/new'
      preLoaderRoute: typeof StocksNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stocks/$id/edit': {
      id: '/stocks/$id/edit'
      path: '/stocks/$id/edit'
      fullPath: '/stocks/$id/edit'
      preLoaderRoute: typeof StocksIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  SummaryRoute: SummaryRoute,
  StocksNewRoute: StocksNewRoute,
  StocksIdEditRoute: StocksIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
