/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StocksIndexRouteImport } from './routes/stocks/index'
import { Route as StocksNewRouteImport } from './routes/stocks/new'
import { Route as StocksIdEditRouteImport } from './routes/stocks/$id/edit'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StocksIndexRoute = StocksIndexRouteImport.update({
  id: '/stocks/',
  path: '/stocks/',
  getParentRoute: () => rootRouteImport,
} as any)
const StocksNewRoute = StocksNewRouteImport.update({
  id: '/stocks/new',
  path: '/stocks/new',
  getParentRoute: () => rootRouteImport,
} as any)
const StocksIdEditRoute = StocksIdEditRouteImport.update({
  id: '/stocks/$id/edit',
  path: '/stocks/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/settings': typeof SettingsRoute
  '/stocks/new': typeof StocksNewRoute
  '/stocks': typeof StocksIndexRoute
  '/stocks/$id/edit': typeof StocksIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/settings': typeof SettingsRoute
  '/stocks/new': typeof StocksNewRoute
  '/stocks': typeof StocksIndexRoute
  '/stocks/$id/edit': typeof StocksIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/settings': typeof SettingsRoute
  '/stocks/new': typeof StocksNewRoute
  '/stocks/': typeof StocksIndexRoute
  '/stocks/$id/edit': typeof StocksIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/settings'
    | '/stocks/new'
    | '/stocks'
    | '/stocks/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/settings'
    | '/stocks/new'
    | '/stocks'
    | '/stocks/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/settings'
    | '/stocks/new'
    | '/stocks/'
    | '/stocks/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  SettingsRoute: typeof SettingsRoute
  StocksNewRoute: typeof StocksNewRoute
  StocksIndexRoute: typeof StocksIndexRoute
  StocksIdEditRoute: typeof StocksIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stocks/': {
      id: '/stocks/'
      path: '/stocks'
      fullPath: '/stocks'
      preLoaderRoute: typeof StocksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stocks/new': {
      id: '/stocks/new'
      path: '/stocks/new'
      fullPath: '/stocks/new'
      preLoaderRoute: typeof StocksNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stocks/$id/edit': {
      id: '/stocks/$id/edit'
      path: '/stocks/$id/edit'
      fullPath: '/stocks/$id/edit'
      preLoaderRoute: typeof StocksIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  SettingsRoute: SettingsRoute,
  StocksNewRoute: StocksNewRoute,
  StocksIndexRoute: StocksIndexRoute,
  StocksIdEditRoute: StocksIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
