packages:
  - packages/server/api
  - packages/client/web
  - packages/client/budget
  - packages/client/portfolio
  - packages/client/mf-scraper

minimumReleaseAge: 2880

onlyBuiltDependencies:
  - bcrypt
  - esbuild
  - sqlite3
