/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SubscriptionIndexRouteImport } from './routes/subscription/index'
import { Route as CashFlowIndexRouteImport } from './routes/cash-flow/index'
import { Route as SubscriptionAddRouteImport } from './routes/subscription/add'
import { Route as HistoryNameRouteImport } from './routes/history/$name'
import { Route as SubscriptionIdIndexRouteImport } from './routes/subscription/$id/index'
import { Route as SubscriptionIdEditRouteImport } from './routes/subscription/$id/edit'
import { Route as CashFlowIncomeAddRouteImport } from './routes/cash-flow/income/add'
import { Route as CashFlowExpenseAddRouteImport } from './routes/cash-flow/expense/add'
import { Route as CashFlowIncomeIdIndexRouteImport } from './routes/cash-flow/income/$id/index'
import { Route as CashFlowExpenseIdIndexRouteImport } from './routes/cash-flow/expense/$id/index'
import { Route as CashFlowIncomeIdEditRouteImport } from './routes/cash-flow/income/$id/edit'
import { Route as CashFlowExpenseIdEditRouteImport } from './routes/cash-flow/expense/$id/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionIndexRoute = SubscriptionIndexRouteImport.update({
  id: '/subscription/',
  path: '/subscription/',
  getParentRoute: () => rootRouteImport,
} as any)
const CashFlowIndexRoute = CashFlowIndexRouteImport.update({
  id: '/cash-flow/',
  path: '/cash-flow/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionAddRoute = SubscriptionAddRouteImport.update({
  id: '/subscription/add',
  path: '/subscription/add',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryNameRoute = HistoryNameRouteImport.update({
  id: '/history/$name',
  path: '/history/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionIdIndexRoute = SubscriptionIdIndexRouteImport.update({
  id: '/subscription/$id/',
  path: '/subscription/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionIdEditRoute = SubscriptionIdEditRouteImport.update({
  id: '/subscription/$id/edit',
  path: '/subscription/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const CashFlowIncomeAddRoute = CashFlowIncomeAddRouteImport.update({
  id: '/cash-flow/income/add',
  path: '/cash-flow/income/add',
  getParentRoute: () => rootRouteImport,
} as any)
const CashFlowExpenseAddRoute = CashFlowExpenseAddRouteImport.update({
  id: '/cash-flow/expense/add',
  path: '/cash-flow/expense/add',
  getParentRoute: () => rootRouteImport,
} as any)
const CashFlowIncomeIdIndexRoute = CashFlowIncomeIdIndexRouteImport.update({
  id: '/cash-flow/income/$id/',
  path: '/cash-flow/income/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const CashFlowExpenseIdIndexRoute = CashFlowExpenseIdIndexRouteImport.update({
  id: '/cash-flow/expense/$id/',
  path: '/cash-flow/expense/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const CashFlowIncomeIdEditRoute = CashFlowIncomeIdEditRouteImport.update({
  id: '/cash-flow/income/$id/edit',
  path: '/cash-flow/income/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const CashFlowExpenseIdEditRoute = CashFlowExpenseIdEditRouteImport.update({
  id: '/cash-flow/expense/$id/edit',
  path: '/cash-flow/expense/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history/$name': typeof HistoryNameRoute
  '/subscription/add': typeof SubscriptionAddRoute
  '/cash-flow': typeof CashFlowIndexRoute
  '/subscription': typeof SubscriptionIndexRoute
  '/cash-flow/expense/add': typeof CashFlowExpenseAddRoute
  '/cash-flow/income/add': typeof CashFlowIncomeAddRoute
  '/subscription/$id/edit': typeof SubscriptionIdEditRoute
  '/subscription/$id': typeof SubscriptionIdIndexRoute
  '/cash-flow/expense/$id/edit': typeof CashFlowExpenseIdEditRoute
  '/cash-flow/income/$id/edit': typeof CashFlowIncomeIdEditRoute
  '/cash-flow/expense/$id': typeof CashFlowExpenseIdIndexRoute
  '/cash-flow/income/$id': typeof CashFlowIncomeIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history/$name': typeof HistoryNameRoute
  '/subscription/add': typeof SubscriptionAddRoute
  '/cash-flow': typeof CashFlowIndexRoute
  '/subscription': typeof SubscriptionIndexRoute
  '/cash-flow/expense/add': typeof CashFlowExpenseAddRoute
  '/cash-flow/income/add': typeof CashFlowIncomeAddRoute
  '/subscription/$id/edit': typeof SubscriptionIdEditRoute
  '/subscription/$id': typeof SubscriptionIdIndexRoute
  '/cash-flow/expense/$id/edit': typeof CashFlowExpenseIdEditRoute
  '/cash-flow/income/$id/edit': typeof CashFlowIncomeIdEditRoute
  '/cash-flow/expense/$id': typeof CashFlowExpenseIdIndexRoute
  '/cash-flow/income/$id': typeof CashFlowIncomeIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/history/$name': typeof HistoryNameRoute
  '/subscription/add': typeof SubscriptionAddRoute
  '/cash-flow/': typeof CashFlowIndexRoute
  '/subscription/': typeof SubscriptionIndexRoute
  '/cash-flow/expense/add': typeof CashFlowExpenseAddRoute
  '/cash-flow/income/add': typeof CashFlowIncomeAddRoute
  '/subscription/$id/edit': typeof SubscriptionIdEditRoute
  '/subscription/$id/': typeof SubscriptionIdIndexRoute
  '/cash-flow/expense/$id/edit': typeof CashFlowExpenseIdEditRoute
  '/cash-flow/income/$id/edit': typeof CashFlowIncomeIdEditRoute
  '/cash-flow/expense/$id/': typeof CashFlowExpenseIdIndexRoute
  '/cash-flow/income/$id/': typeof CashFlowIncomeIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/history/$name'
    | '/subscription/add'
    | '/cash-flow'
    | '/subscription'
    | '/cash-flow/expense/add'
    | '/cash-flow/income/add'
    | '/subscription/$id/edit'
    | '/subscription/$id'
    | '/cash-flow/expense/$id/edit'
    | '/cash-flow/income/$id/edit'
    | '/cash-flow/expense/$id'
    | '/cash-flow/income/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/history/$name'
    | '/subscription/add'
    | '/cash-flow'
    | '/subscription'
    | '/cash-flow/expense/add'
    | '/cash-flow/income/add'
    | '/subscription/$id/edit'
    | '/subscription/$id'
    | '/cash-flow/expense/$id/edit'
    | '/cash-flow/income/$id/edit'
    | '/cash-flow/expense/$id'
    | '/cash-flow/income/$id'
  id:
    | '__root__'
    | '/'
    | '/history/$name'
    | '/subscription/add'
    | '/cash-flow/'
    | '/subscription/'
    | '/cash-flow/expense/add'
    | '/cash-flow/income/add'
    | '/subscription/$id/edit'
    | '/subscription/$id/'
    | '/cash-flow/expense/$id/edit'
    | '/cash-flow/income/$id/edit'
    | '/cash-flow/expense/$id/'
    | '/cash-flow/income/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryNameRoute: typeof HistoryNameRoute
  SubscriptionAddRoute: typeof SubscriptionAddRoute
  CashFlowIndexRoute: typeof CashFlowIndexRoute
  SubscriptionIndexRoute: typeof SubscriptionIndexRoute
  CashFlowExpenseAddRoute: typeof CashFlowExpenseAddRoute
  CashFlowIncomeAddRoute: typeof CashFlowIncomeAddRoute
  SubscriptionIdEditRoute: typeof SubscriptionIdEditRoute
  SubscriptionIdIndexRoute: typeof SubscriptionIdIndexRoute
  CashFlowExpenseIdEditRoute: typeof CashFlowExpenseIdEditRoute
  CashFlowIncomeIdEditRoute: typeof CashFlowIncomeIdEditRoute
  CashFlowExpenseIdIndexRoute: typeof CashFlowExpenseIdIndexRoute
  CashFlowIncomeIdIndexRoute: typeof CashFlowIncomeIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription/': {
      id: '/subscription/'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof SubscriptionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cash-flow/': {
      id: '/cash-flow/'
      path: '/cash-flow'
      fullPath: '/cash-flow'
      preLoaderRoute: typeof CashFlowIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription/add': {
      id: '/subscription/add'
      path: '/subscription/add'
      fullPath: '/subscription/add'
      preLoaderRoute: typeof SubscriptionAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/$name': {
      id: '/history/$name'
      path: '/history/$name'
      fullPath: '/history/$name'
      preLoaderRoute: typeof HistoryNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription/$id/': {
      id: '/subscription/$id/'
      path: '/subscription/$id'
      fullPath: '/subscription/$id'
      preLoaderRoute: typeof SubscriptionIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription/$id/edit': {
      id: '/subscription/$id/edit'
      path: '/subscription/$id/edit'
      fullPath: '/subscription/$id/edit'
      preLoaderRoute: typeof SubscriptionIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cash-flow/income/add': {
      id: '/cash-flow/income/add'
      path: '/cash-flow/income/add'
      fullPath: '/cash-flow/income/add'
      preLoaderRoute: typeof CashFlowIncomeAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cash-flow/expense/add': {
      id: '/cash-flow/expense/add'
      path: '/cash-flow/expense/add'
      fullPath: '/cash-flow/expense/add'
      preLoaderRoute: typeof CashFlowExpenseAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cash-flow/income/$id/': {
      id: '/cash-flow/income/$id/'
      path: '/cash-flow/income/$id'
      fullPath: '/cash-flow/income/$id'
      preLoaderRoute: typeof CashFlowIncomeIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cash-flow/expense/$id/': {
      id: '/cash-flow/expense/$id/'
      path: '/cash-flow/expense/$id'
      fullPath: '/cash-flow/expense/$id'
      preLoaderRoute: typeof CashFlowExpenseIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cash-flow/income/$id/edit': {
      id: '/cash-flow/income/$id/edit'
      path: '/cash-flow/income/$id/edit'
      fullPath: '/cash-flow/income/$id/edit'
      preLoaderRoute: typeof CashFlowIncomeIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cash-flow/expense/$id/edit': {
      id: '/cash-flow/expense/$id/edit'
      path: '/cash-flow/expense/$id/edit'
      fullPath: '/cash-flow/expense/$id/edit'
      preLoaderRoute: typeof CashFlowExpenseIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryNameRoute: HistoryNameRoute,
  SubscriptionAddRoute: SubscriptionAddRoute,
  CashFlowIndexRoute: CashFlowIndexRoute,
  SubscriptionIndexRoute: SubscriptionIndexRoute,
  CashFlowExpenseAddRoute: CashFlowExpenseAddRoute,
  CashFlowIncomeAddRoute: CashFlowIncomeAddRoute,
  SubscriptionIdEditRoute: SubscriptionIdEditRoute,
  SubscriptionIdIndexRoute: SubscriptionIdIndexRoute,
  CashFlowExpenseIdEditRoute: CashFlowExpenseIdEditRoute,
  CashFlowIncomeIdEditRoute: CashFlowIncomeIdEditRoute,
  CashFlowExpenseIdIndexRoute: CashFlowExpenseIdIndexRoute,
  CashFlowIncomeIdIndexRoute: CashFlowIncomeIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
