import { css } from '../../../styled-system/css';

export const newAggregationStyles = {
    page: css({
        display: 'flex',
        flexDirection: 'column',
        gap: '1.5rem',
    }),
    header: css({
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
    }),
    title: css({
        fontSize: 'xl',
        fontWeight: 'bold',
        color: 'gray.800',
        margin: 0,
    }),
    form: css({
        display: 'flex',
        flexDirection: 'column',
        gap: '1.5rem',
    }),
    section: css({
        backgroundColor: 'white',
        borderRadius: 'lg',
        padding: '1rem',
        boxShadow: 'sm',
    }),
    sectionTitle: css({
        fontSize: 'md',
        fontWeight: 'semibold',
        color: 'gray.700',
        marginBottom: '1rem',
    }),
    field: css({
        display: 'flex',
        flexDirection: 'column',
        gap: '0.5rem',
        marginBottom: '1rem',
    }),
    label: css({
        fontSize: 'sm',
        fontWeight: 'medium',
        color: 'gray.700',
    }),
    input: css({
        padding: '0.5rem 0.75rem',
        borderRadius: 'md',
        border: '1px solid',
        borderColor: 'gray.300',
        fontSize: 'sm',
        _focus: {
            borderColor: 'green.500',
            outline: 'none',
            boxShadow: '0 0 0 1px var(--colors-green-500)',
        },
    }),
    inputError: css({
        borderColor: 'red.500',
    }),
    error: css({
        fontSize: 'xs',
        color: 'red.600',
    }),
    attributeList: css({
        display: 'flex',
        flexDirection: 'column',
        gap: '0.75rem',
    }),
    attributeItem: css({
        display: 'flex',
        gap: '0.5rem',
        alignItems: 'center',
        padding: '0.5rem',
        backgroundColor: 'gray.50',
        borderRadius: 'md',
    }),
    colorInput: css({
        width: '40px',
        height: '32px',
        padding: '2px',
        border: '1px solid',
        borderColor: 'gray.300',
        borderRadius: 'md',
        cursor: 'pointer',
    }),
    removeButton: css({
        padding: '0.25rem 0.5rem',
        backgroundColor: 'red.100',
        color: 'red.700',
        border: 'none',
        borderRadius: 'sm',
        fontSize: 'xs',
        cursor: 'pointer',
        _hover: {
            backgroundColor: 'red.200',
        },
    }),
    addAttributeButton: css({
        padding: '0.5rem 1rem',
        backgroundColor: 'gray.100',
        color: 'gray.700',
        border: '1px dashed',
        borderColor: 'gray.300',
        borderRadius: 'md',
        fontSize: 'sm',
        cursor: 'pointer',
        _hover: {
            backgroundColor: 'gray.200',
        },
    }),
    stockList: css({
        display: 'flex',
        flexDirection: 'column',
        gap: '0.5rem',
    }),
    stockItem: css({
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: '0.75rem',
        backgroundColor: 'gray.50',
        borderRadius: 'md',
    }),
    stockInfo: css({
        display: 'flex',
        flexDirection: 'column',
    }),
    stockTicker: css({
        fontWeight: 'bold',
        color: 'green.700',
        fontSize: 'sm',
    }),
    stockName: css({
        fontSize: 'xs',
        color: 'gray.600',
    }),
    stockValue: css({
        fontSize: 'xs',
        color: 'gray.500',
    }),
    select: css({
        padding: '0.5rem',
        borderRadius: 'md',
        border: '1px solid',
        borderColor: 'gray.300',
        fontSize: 'sm',
        backgroundColor: 'white',
        minWidth: '120px',
    }),
    buttons: css({
        display: 'flex',
        gap: '1rem',
        justifyContent: 'flex-end',
    }),
    cancelButton: css({
        padding: '0.75rem 1.5rem',
        backgroundColor: 'gray.100',
        color: 'gray.700',
        border: 'none',
        borderRadius: 'md',
        fontSize: 'sm',
        fontWeight: 'medium',
        cursor: 'pointer',
        textDecoration: 'none',
        _hover: {
            backgroundColor: 'gray.200',
        },
    }),
    submitButton: css({
        padding: '0.75rem 1.5rem',
        backgroundColor: 'green.600',
        color: 'white',
        border: 'none',
        borderRadius: 'md',
        fontSize: 'sm',
        fontWeight: 'medium',
        cursor: 'pointer',
        _hover: {
            backgroundColor: 'green.700',
        },
        _disabled: {
            backgroundColor: 'gray.300',
            cursor: 'not-allowed',
        },
    }),
    emptyState: css({
        textAlign: 'center',
        padding: '2rem',
        color: 'gray.500',
        fontSize: 'sm',
    }),
};
